### ISSUE TITLE
Wire is not defined

### ISSUE THREAD

**Issue by rinadyx** [Matheart/manim-physics#28]
Hello everyone, this is my first time using manim, manim-physics and GitHub, i hope that i'm doing every fine and respecting all the rules,

So my issue is that i want to create an animation of a magnetic field streamline being blocked by a metallic shield, and as a starter i wanted to try the code provided in the doc, but when i try to input the Wire example in my visual studio i get this message error : 

"Wire" is not defined Pylance (reportUndefinedVariable) [Ln 7, Col 16],

How can i solve this ? 

Best regards,

**Comment by icedcoffeeee** [comment]
Hello! Sorry for the confusion. The issue was that the new update hadn't been published on PyPI yet. But now it has, so you can run
```bash
pip install -U manim-physics
```
to get the updated code.
