### ISSUE TITLE
Bump manim version requirement

### ISSUE THREAD

**Issue by abul4fia** [Matheart/manim-physics#29]
Manim is currently at version 0.18.0.post0, and remains compatible with manim-physics.

However manim-physics' pyproject specifies:

```toml
manim = "^0.17.3"
```

which causes that any attempt to install manim-physics downgrades installed manim to 0.17.13, and any attempt of upgrading manim after that issues a warning about incompatible requirements with manim-physics.

I think the line in pyproject can be safely changed to:

```toml
manim = "^0.17.3,<0.19.0"
```

**Comment by icedcoffeeee** [comment]
Fixed in #32

**Comment by abul4fia** [comment]
Thanks!

I think you still have to bump manim-physics version and publish it on pypi

**Comment by icedcoffeeee** [comment]
woops you're right, i'll get on that this week
