### ISSUE TITLE
MagneticField() does not work with multiple wires

### ISSUE THREAD

**Issue by uwezi** [Matheart/manim-physics#34]
While all the code is prepared for several wires in the `MagneticField()` class, the field function loop does not work if more than one wire is given as an argument to `MagneticField`

## Code to reproduce the problem
```py
from manim_physics import *

class MagneticFields3(ThreeDScene):
    def construct(self):
        wire1 = Wire(Circle(2).rotate(PI / 2, UP))
        wire2 = Wire(Circle(2).rotate(PI / 2, UP)).shift(1*RIGHT)
        mag_field = MagneticField(
            wire1, wire2,
            #x_range=[-4, 4],
            #y_range=[-4, 4],
        )
        self.set_camera_orientation(PI / 3, PI / 4)
        self.add(wire1, wire2, mag_field)
```

## Necessary changes
In the field function of `MagneticField` the unpacking of the individual wires stored in `dls` needs to be in an outer loop:
```py
    @staticmethod
    def _field_func(
        p: np.ndarray,
        dls: Iterable[Tuple[np.ndarray, np.ndarray]],
        currents: Iterable[float],
    ):
        B_field = np.zeros(3)
        for dl in dls:
            for (r0, r1), I in it.product(dl, currents):
                dl = r1 - r0
                r = p - r0
                dist = np.linalg.norm(r)
                if dist < 0.1:
                    return np.zeros(3)
                B_field += np.cross(dl, r) * I / dist**4
        return B_field
```

## Resulting scene
![bild](https://github.com/user-attachments/assets/94efad4f-fac7-49c7-ab00-e4ca6fcc5c15)

**Comment by icedcoffeeee** [comment]
Thanks for the ticket, didn't realize this wasn't working as intended. Would you like to create a PR?

**Comment by uwezi** [comment]
> Thanks for the ticket, didn't realize this wasn't working as intended. Would you like to create a PR?

Sorry, but I have no time or intentions to create a PR - but I would appreciate if a developer could correct the problem.
